name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        uses: peaceiris/actions-gh-pages@v3  # Verify the action name and version
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: VedhamaniprabakarA/portfolio
          publish_dir: ./build
